server:
  port: 7070

spring:
  application:
    name: Certificate




  mvc:
    view:
      suffix: .html

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spocerti_ver_2?serverTimezone=UTC&characterEncoding=UTF-8
    username: spocerti
    password: 8991
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.spo.certificate._dto.answer,com.spo.certificate._dto.exam,com.spo.certificate._dto.subject,com.spo.certificate._dto.test,com.spo.certificate._dto.user
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    # MyBatis 쿼리 로깅
    com.spo.certificate: DEBUG
    org.mybatis: DEBUG
    org.mybatis.spring: DEBUG

storage:
  receivingPath: D:\spocert\DATA\
